version: '3'

networks:
  default:
    driver: bridge
  webproxy:
    external: true

services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
      - ${STORAGE_MYSQL}:/var/lib/mysql
      - ./configs/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    networks:
      - webproxy
      - default
    depends_on:
      - db
    image: wordpress:latest
    restart: unless-stopped
    volumes:
      - ${STORAGE_WP_CORE}:/var/www/html
      - ${STORAGE_WP_CONTENT}:/var/www/html/wp-content
      - ./configs/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}